# Generated by Django 4.2.16 on 2024-11-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_slug_to_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
